// Re-runnable photo optimizer: resizes curated source folders into
// public/photos/travel/<slug>/ and regenerates src/data/travel-galleries.ts.
// Auto-orients via EXIF then strips ALL metadata (incl. GPS) — sharp drops
// metadata by default. Run: node scripts/optimize-photos.mjs
//
// Robust/incremental: a place whose source folder is missing keeps its already
// -optimized photos. A place with `limit` keeps only the N sharpest images
// (variance-of-Laplacian focus measure) — good for trimming a big dump to the
// clearest frames. The data file is rebuilt by scanning what's on disk.
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const TRAVEL_DIR = path.join(ROOT, "public/photos/travel");

const PLACES = [
  { slug: "ooty", place: "Ooty", state: "Tamil Nadu", src: "C:/Users/ASUS/Downloads/Ooty" },
  { slug: "goa", place: "Goa", state: "Goa", src: "C:/Users/ASUS/Downloads/Goa/iCloud Photos" },
  { slug: "assam", place: "Assam", state: "Assam", src: "C:/Users/ASUS/Downloads/Assam/iCloud Photos" },
  { slug: "chettinad", place: "Chettinad", state: "Tamil Nadu", src: "C:/Users/ASUS/Downloads/Chettinadu/iCloud Photos" },
  // Big dump → keep only the 18 sharpest frames.
  { slug: "westcoast-ka", place: "Chikmagalur", state: "Karnataka", src: "C:/Users/ASUS/Downloads/westcoast-ka/iCloud Photos", limit: 18 },
];

const isImage = (f) => /\.(jpe?g|png|heic)$/i.test(f);

// Variance-of-Laplacian focus measure: higher = sharper / more in focus.
async function sharpness(file) {
  const { channels } = await sharp(file)
    .greyscale()
    .resize(512, 512, { fit: "inside" })
    .convolve({ width: 3, height: 3, kernel: [0, 1, 0, 1, -4, 1, 0, 1, 0] })
    .stats();
  return channels[0].stdev;
}

async function selectFiles(dir, files, limit) {
  if (!limit || files.length <= limit) return files;
  const scored = [];
  for (const f of files) {
    try {
      scored.push({ f, s: await sharpness(path.join(dir, f)) });
    } catch {
      scored.push({ f, s: 0 });
    }
  }
  scored.sort((a, b) => b.s - a.s);
  const kept = new Set(scored.slice(0, limit).map((x) => x.f));
  return files.filter((f) => kept.has(f)); // keep original (filename) order
}

for (const p of PLACES) {
  const outDir = path.join(TRAVEL_DIR, p.slug);
  if (p.src && fs.existsSync(p.src)) {
    fs.rmSync(outDir, { recursive: true, force: true });
    fs.mkdirSync(outDir, { recursive: true });
    const all = fs.readdirSync(p.src).filter(isImage).sort();
    const files = await selectFiles(p.src, all, p.limit);
    let i = 0;
    for (const f of files) {
      i += 1;
      const name = `${p.slug}-${String(i).padStart(2, "0")}.jpg`;
      await sharp(path.join(p.src, f))
        .rotate()
        .resize({ width: 2000, height: 2000, fit: "inside", withoutEnlargement: true })
        .jpeg({ quality: 80, mozjpeg: true })
        .toFile(path.join(outDir, name));
    }
    console.log(`${p.place}: kept ${i}${p.limit ? ` of ${all.length} (sharpest)` : ""}`);
  } else if (fs.existsSync(outDir)) {
    console.log(`${p.place}: source missing — keeping ${fs.readdirSync(outDir).length} existing photos`);
  } else {
    console.log(`${p.place}: no source and nothing on disk — skipped`);
  }
}

// Rebuild the data file from what's actually on disk.
const galleries = [];
for (const p of PLACES) {
  const outDir = path.join(TRAVEL_DIR, p.slug);
  if (!fs.existsSync(outDir)) continue;
  const photos = fs
    .readdirSync(outDir)
    .filter((f) => /\.jpg$/i.test(f))
    .sort()
    .map((f) => `/photos/travel/${p.slug}/${f}`);
  if (photos.length) galleries.push({ slug: p.slug, place: p.place, state: p.state, photos });
}

const ts = `// AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
export type PlaceGallery = { slug: string; place: string; state: string; photos: string[] };

export const TRAVEL_GALLERIES: PlaceGallery[] = ${JSON.stringify(galleries, null, 2)};
`;
fs.writeFileSync(path.join(ROOT, "src/data/travel-galleries.ts"), ts);
console.log(`Wrote src/data/travel-galleries.ts (${galleries.length} galleries)`);
