// One-off (re-runnable) photo optimizer: resizes curated source folders into
// public/photos/travel/<slug>/ and regenerates src/data/travel-galleries.ts.
// Auto-orients via EXIF then strips ALL metadata (incl. GPS) — sharp drops
// metadata by default. Run: node scripts/optimize-photos.mjs
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const PLACES = [
  { slug: "ooty", place: "Ooty", state: "Tamil Nadu", src: "C:/Users/ASUS/Downloads/Ooty" },
  { slug: "goa", place: "Goa", state: "Goa", src: "C:/Users/ASUS/Downloads/Goa/iCloud Photos" },
  { slug: "assam", place: "Assam", state: "Assam", src: "C:/Users/ASUS/Downloads/Assam/iCloud Photos" },
];

const isImage = (f) => /\.(jpe?g|png|heic)$/i.test(f);
const galleries = [];

for (const p of PLACES) {
  const outDir = path.join(ROOT, "public/photos/travel", p.slug);
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  const files = fs.readdirSync(p.src).filter(isImage).sort();
  const photos = [];
  let i = 0;
  for (const f of files) {
    i += 1;
    const name = `${p.slug}-${String(i).padStart(2, "0")}.jpg`;
    await sharp(path.join(p.src, f))
      .rotate() // apply EXIF orientation, then metadata is dropped
      .resize({ width: 2000, height: 2000, fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: 80, mozjpeg: true })
      .toFile(path.join(outDir, name));
    photos.push(`/photos/travel/${p.slug}/${name}`);
  }
  galleries.push({ slug: p.slug, place: p.place, state: p.state, photos });
  console.log(`${p.place}: ${photos.length} photos`);
}

const ts = `// AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
export type PlaceGallery = { slug: string; place: string; state: string; photos: string[] };

export const TRAVEL_GALLERIES: PlaceGallery[] = ${JSON.stringify(galleries, null, 2)};
`;
fs.writeFileSync(path.join(ROOT, "src/data/travel-galleries.ts"), ts);
console.log("Wrote src/data/travel-galleries.ts");
