// AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
export type CricketGallery = { slug: string; title: string; photos: string[] };

export const CRICKET_GALLERIES = [
  {
    "slug": "cricket",
    "title": "On the field",
    "photos": [
      "/photos/cricket/cricket/cricket-01.jpg",
      "/photos/cricket/cricket/cricket-02.jpg"
    ]
  }
];
