// AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
export type MovementGallery = { slug: string; title: string; photos: string[] };

export const MOVEMENT_GALLERIES = [
  {
    "slug": "trekking",
    "title": "On the trail",
    "photos": [
      "/photos/movement/trekking/trekking-01.jpg",
      "/photos/movement/trekking/trekking-02.jpg",
      "/photos/movement/trekking/trekking-03.jpg",
      "/photos/movement/trekking/trekking-04.jpg",
      "/photos/movement/trekking/trekking-05.jpg",
      "/photos/movement/trekking/trekking-06.jpg",
      "/photos/movement/trekking/trekking-07.jpg",
      "/photos/movement/trekking/trekking-08.jpg",
      "/photos/movement/trekking/trekking-09.jpg",
      "/photos/movement/trekking/trekking-10.jpg",
      "/photos/movement/trekking/trekking-11.jpg",
      "/photos/movement/trekking/trekking-12.jpg",
      "/photos/movement/trekking/trekking-13.jpg",
      "/photos/movement/trekking/trekking-14.jpg",
      "/photos/movement/trekking/trekking-15.jpg",
      "/photos/movement/trekking/trekking-16.jpg",
      "/photos/movement/trekking/trekking-17.jpg",
      "/photos/movement/trekking/trekking-18.jpg",
      "/photos/movement/trekking/trekking-19.jpg",
      "/photos/movement/trekking/trekking-20.jpg"
    ]
  }
];
