// AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
export type PlaceGallery = { slug: string; place: string; state: string; photos: string[] };

export const TRAVEL_GALLERIES: PlaceGallery[] = [
  {
    "slug": "ooty",
    "place": "Ooty",
    "state": "Tamil Nadu",
    "photos": [
      "/photos/travel/ooty/ooty-01.jpg",
      "/photos/travel/ooty/ooty-02.jpg",
      "/photos/travel/ooty/ooty-03.jpg",
      "/photos/travel/ooty/ooty-04.jpg",
      "/photos/travel/ooty/ooty-05.jpg",
      "/photos/travel/ooty/ooty-06.jpg",
      "/photos/travel/ooty/ooty-07.jpg",
      "/photos/travel/ooty/ooty-08.jpg",
      "/photos/travel/ooty/ooty-09.jpg",
      "/photos/travel/ooty/ooty-10.jpg",
      "/photos/travel/ooty/ooty-11.jpg",
      "/photos/travel/ooty/ooty-12.jpg",
      "/photos/travel/ooty/ooty-13.jpg"
    ]
  },
  {
    "slug": "goa",
    "place": "Goa",
    "state": "Goa",
    "photos": [
      "/photos/travel/goa/goa-01.jpg",
      "/photos/travel/goa/goa-02.jpg",
      "/photos/travel/goa/goa-03.jpg",
      "/photos/travel/goa/goa-04.jpg",
      "/photos/travel/goa/goa-05.jpg",
      "/photos/travel/goa/goa-06.jpg",
      "/photos/travel/goa/goa-07.jpg",
      "/photos/travel/goa/goa-08.jpg",
      "/photos/travel/goa/goa-09.jpg",
      "/photos/travel/goa/goa-10.jpg",
      "/photos/travel/goa/goa-11.jpg",
      "/photos/travel/goa/goa-12.jpg",
      "/photos/travel/goa/goa-13.jpg",
      "/photos/travel/goa/goa-14.jpg",
      "/photos/travel/goa/goa-15.jpg",
      "/photos/travel/goa/goa-16.jpg",
      "/photos/travel/goa/goa-17.jpg",
      "/photos/travel/goa/goa-18.jpg"
    ]
  },
  {
    "slug": "assam",
    "place": "Assam",
    "state": "Assam",
    "photos": [
      "/photos/travel/assam/assam-01.jpg",
      "/photos/travel/assam/assam-02.jpg",
      "/photos/travel/assam/assam-03.jpg",
      "/photos/travel/assam/assam-04.jpg",
      "/photos/travel/assam/assam-05.jpg",
      "/photos/travel/assam/assam-06.jpg",
      "/photos/travel/assam/assam-07.jpg",
      "/photos/travel/assam/assam-08.jpg",
      "/photos/travel/assam/assam-09.jpg",
      "/photos/travel/assam/assam-10.jpg",
      "/photos/travel/assam/assam-11.jpg",
      "/photos/travel/assam/assam-12.jpg"
    ]
  },
  {
    "slug": "chettinad",
    "place": "Chettinad",
    "state": "Tamil Nadu",
    "photos": [
      "/photos/travel/chettinad/chettinad-01.jpg",
      "/photos/travel/chettinad/chettinad-02.jpg",
      "/photos/travel/chettinad/chettinad-03.jpg",
      "/photos/travel/chettinad/chettinad-04.jpg",
      "/photos/travel/chettinad/chettinad-05.jpg",
      "/photos/travel/chettinad/chettinad-06.jpg",
      "/photos/travel/chettinad/chettinad-07.jpg",
      "/photos/travel/chettinad/chettinad-08.jpg",
      "/photos/travel/chettinad/chettinad-09.jpg",
      "/photos/travel/chettinad/chettinad-10.jpg"
    ]
  },
  {
    "slug": "kashmir",
    "place": "Kashmir",
    "state": "Jammu & Kashmir",
    "photos": [
      "/photos/travel/kashmir/kashmir-01.jpg",
      "/photos/travel/kashmir/kashmir-02.jpg",
      "/photos/travel/kashmir/kashmir-03.jpg",
      "/photos/travel/kashmir/kashmir-04.jpg",
      "/photos/travel/kashmir/kashmir-05.jpg",
      "/photos/travel/kashmir/kashmir-06.jpg",
      "/photos/travel/kashmir/kashmir-07.jpg",
      "/photos/travel/kashmir/kashmir-08.jpg"
    ]
  },
  {
    "slug": "ladakh",
    "place": "Ladakh",
    "state": "Ladakh",
    "photos": [
      "/photos/travel/ladakh/ladakh-01.jpg",
      "/photos/travel/ladakh/ladakh-02.jpg",
      "/photos/travel/ladakh/ladakh-03.jpg",
      "/photos/travel/ladakh/ladakh-04.jpg",
      "/photos/travel/ladakh/ladakh-05.jpg",
      "/photos/travel/ladakh/ladakh-06.jpg",
      "/photos/travel/ladakh/ladakh-07.jpg",
      "/photos/travel/ladakh/ladakh-08.jpg",
      "/photos/travel/ladakh/ladakh-09.jpg",
      "/photos/travel/ladakh/ladakh-10.jpg",
      "/photos/travel/ladakh/ladakh-11.jpg",
      "/photos/travel/ladakh/ladakh-12.jpg",
      "/photos/travel/ladakh/ladakh-13.jpg",
      "/photos/travel/ladakh/ladakh-14.jpg",
      "/photos/travel/ladakh/ladakh-15.jpg",
      "/photos/travel/ladakh/ladakh-16.jpg",
      "/photos/travel/ladakh/ladakh-17.jpg",
      "/photos/travel/ladakh/ladakh-18.jpg",
      "/photos/travel/ladakh/ladakh-19.jpg",
      "/photos/travel/ladakh/ladakh-20.jpg"
    ]
  },
  {
    "slug": "westcoast-ka",
    "place": "Chikmagalur",
    "state": "Karnataka",
    "photos": [
      "/photos/travel/westcoast-ka/westcoast-ka-01.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-02.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-03.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-04.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-05.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-06.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-07.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-08.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-09.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-10.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-11.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-12.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-13.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-14.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-15.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-16.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-17.jpg",
      "/photos/travel/westcoast-ka/westcoast-ka-18.jpg"
    ]
  }
];
