// AUTO-GENERATED by scripts/optimize-photos.mjs — do not edit by hand.
export type PlaceGallery = { slug: string; place: string; state: string; photos: string[] };

export const TRAVEL_GALLERIES: PlaceGallery[] = [
  {
    "slug": "ooty",
    "place": "Ooty",
    "state": "Tamil Nadu",
    "photos": [
      "/photos/travel/ooty/ooty-01.jpg",
      "/photos/travel/ooty/ooty-02.jpg",
      "/photos/travel/ooty/ooty-03.jpg",
      "/photos/travel/ooty/ooty-04.jpg",
      "/photos/travel/ooty/ooty-05.jpg",
      "/photos/travel/ooty/ooty-06.jpg",
      "/photos/travel/ooty/ooty-07.jpg",
      "/photos/travel/ooty/ooty-08.jpg",
      "/photos/travel/ooty/ooty-09.jpg",
      "/photos/travel/ooty/ooty-10.jpg",
      "/photos/travel/ooty/ooty-11.jpg",
      "/photos/travel/ooty/ooty-12.jpg",
      "/photos/travel/ooty/ooty-13.jpg"
    ]
  },
  {
    "slug": "goa",
    "place": "Goa",
    "state": "Goa",
    "photos": [
      "/photos/travel/goa/goa-01.jpg",
      "/photos/travel/goa/goa-02.jpg",
      "/photos/travel/goa/goa-03.jpg",
      "/photos/travel/goa/goa-04.jpg",
      "/photos/travel/goa/goa-05.jpg",
      "/photos/travel/goa/goa-06.jpg",
      "/photos/travel/goa/goa-07.jpg",
      "/photos/travel/goa/goa-08.jpg",
      "/photos/travel/goa/goa-09.jpg",
      "/photos/travel/goa/goa-10.jpg",
      "/photos/travel/goa/goa-11.jpg",
      "/photos/travel/goa/goa-12.jpg",
      "/photos/travel/goa/goa-13.jpg",
      "/photos/travel/goa/goa-14.jpg",
      "/photos/travel/goa/goa-15.jpg",
      "/photos/travel/goa/goa-16.jpg",
      "/photos/travel/goa/goa-17.jpg",
      "/photos/travel/goa/goa-18.jpg"
    ]
  },
  {
    "slug": "assam",
    "place": "Assam",
    "state": "Assam",
    "photos": [
      "/photos/travel/assam/assam-01.jpg",
      "/photos/travel/assam/assam-02.jpg",
      "/photos/travel/assam/assam-03.jpg",
      "/photos/travel/assam/assam-04.jpg",
      "/photos/travel/assam/assam-05.jpg",
      "/photos/travel/assam/assam-06.jpg",
      "/photos/travel/assam/assam-07.jpg",
      "/photos/travel/assam/assam-08.jpg",
      "/photos/travel/assam/assam-09.jpg",
      "/photos/travel/assam/assam-10.jpg",
      "/photos/travel/assam/assam-11.jpg",
      "/photos/travel/assam/assam-12.jpg"
    ]
  }
];
